//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public int Grade { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateLeft { get; set; }
        public string UserId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
