//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.FilterItems = new HashSet<FilterItem>();
            this.Filters = new HashSet<Filter>();
        }
    
        public int Id { get; set; }
        public string Header { get; set; }
        public string Discription { get; set; }
        public decimal Price { get; set; }
        public int Views { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string UserProfileId { get; set; }
        public int GameId { get; set; }
        public int State { get; set; }
        public bool SellerPaysMiddleman { get; set; }
        public decimal MiddlemanPrice { get; set; }
        public string AccountLogin { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilterItem> FilterItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filter> Filters { get; set; }
    }
}
