//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int OrderId { get; set; }
        public string FinisedName { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
