// <auto-generated />
namespace Market.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171804347_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
